(cl:defpackage shared_serial-srv
  (:use )
  (:export
   "SENDTO"
   "<SENDTO-REQUEST>"
   "SENDTO-REQUEST"
   "<SENDTO-RESPONSE>"
   "SENDTO-RESPONSE"
   "CONNECT"
   "<CONNECT-REQUEST>"
   "CONNECT-REQUEST"
   "<CONNECT-RESPONSE>"
   "CONNECT-RESPONSE"
   "RECV"
   "<RECV-REQUEST>"
   "RECV-REQUEST"
   "<RECV-RESPONSE>"
   "RECV-RESPONSE"
   "SENDRECV"
   "<SENDRECV-REQUEST>"
   "SENDRECV-REQUEST"
   "<SENDRECV-RESPONSE>"
   "SENDRECV-RESPONSE"
  ))

